# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
fail_fast: true
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
  - repo: local
    hooks:
      - id: isort
        name: sort imports
        entry: uv run --active ruff check --select I --fix
        pass_filenames: false
        language: system
        types: [python]
      - id: black
        name: format code
        entry: uv run --active ruff format
        pass_filenames: false
        language: system
        types: [python]
      - id: pytest
        name: pytest-check
        entry: uv run --active pytest tests
        language: system
        pass_filenames: false
        types: [python]
default_language_version:
  python: python3
