# AUTO-GENERATED BY scripts/generate_opfeats.py
# Source: js/snippet/U.js
# Do not edit manually.

from typing import Tuple

# fmt: off
OP_COUNT: int = 58

OP_NAMES: Tuple[str, ...] = (
    "getattr",
    "inst",
    "stepout",
    "geq",
    "copy",
    "inv",
    "arr_popleft",
    "grwinattr",
    "zstr",
    "clear",
    "eq",
    "vm_factory",
    "assign",
    "typeof",
    "outcall",
    "new",
    "inst_arr",
    "stop",
    "swap",
    "check_err",
    "throw",
    "contains",
    "setattr",
    "add",
    "n2list",
    "chobj",
    "getobj",
    "refeq",
    "stepin",
    "group",
    "wincall",
    "drop",
    "undefined",
    "jump",
    "mul",
    "je",
    "ge",
    "rshift",
    "mod",
    "delattr",
    "false",
    "get_global",
    "bitor",
    "sub",
    "xor",
    "grobj",
    "new_attr",
    "true",
    "getobj2",
    "bitand",
    "urshift",
    "realloc",
    "tolist",
    "div",
    "grgetattr",
    "lshift",
    "null",
    "concat",
)

OP_SYNTAX: Tuple[str, ...] = (
    "t0=S[pop]();S[push](t0[0][t0[1]])",  # 0: getattr
    "S[push](P[++])",  # 1: inst
    "t0[pop]()",  # 2: stepout
    "S[S[length]-2]=S[S[length]-2]>=S[pop]()",  # 3: geq
    "S[push](S[S[length]-1])",  # 4: copy
    "S[push](!S[pop]())",  # 5: inv
    "S[S[length]-1][length]?(S[push](S[S[length]-1][shift](),!0)):(S[push](undefined,!1))",  # 6: arr_popleft
    "S[push]([window,S[pop]()])",  # 7: grwinattr
    "S[push]('')",  # 8: zstr
    "t0=null",  # 9: clear
    "S[S[length]-2]=S[S[length]-2]==S[pop]()",  # 10: eq
    "for;for;S[push](fun t0(){t1=t2[slice](0);t1[0]=[];t1[1]=[arguments];t1[2]=[t0];for;return __TENCENT_CHAOS_VM(t3,P,window,t1,t4,t5,t6,t7)})",  # 11: vm_factory
    "S[S[length]-1]=P[++]",  # 12: assign
    "S[push](typeofS[pop]())",  # 13: typeof
    "t0=P[++];t1=t0?(S[slice](-t0)):([]);S[length]-=t0;t0=S[pop]();S[push](t0[0][t0[1]][apply](t0[0],t1))",  # 14: outcall
    "t0=P[++];t1=t0?(S[slice](-t0)):([]);S[length]-=t0;t1[unshift](null);S[push](t2(S[pop](),t1))",  # 15: new
    "S[push]([P[++]])",  # 16: inst_arr
    "return !0",  # 17: stop
    "t0=P[++];t1=S[S[length]-2-t0];S[S[length]-2-t0]=S[pop]();S[push](t1)",  # 18: swap
    "return !!t0",  # 19: check_err
    "throw S[S[length]-1]",  # 20: throw
    "S[S[length]-2]=S[S[length]-2]inS[pop]()",  # 21: contains
    "t0=S[S[length]-2];t0[0][t0[1]]=S[S[length]-1]",  # 22: setattr
    "S[S[length]-2]=S[S[length]-2]+S[pop]()",  # 23: add
    "t0=P[++];S[t0]=S[t0]===undefined?([]):(S[t0])",  # 24: n2list
    "S[S[S[length]-2][0]][0]=S[S[length]-1]",  # 25: chobj
    "S[push](S[P[++]][0])",  # 26: getobj
    "S[S[length]-2]=S[S[length]-2]===S[pop]()",  # 27: refeq
    "t0[push]([P[++],S[length],P[++]])",  # 28: stepin
    "S[push]([S[pop](),S[pop]()][reverse]())",  # 29: group
    "t0=P[++];t1=t0?(S[slice](-t0)):([]);S[length]-=t0;S[push](S[pop]()[apply](window,t1))",  # 30: wincall
    "S[pop]()",  # 31: drop
    "S[push](undefined)",  # 32: undefined
    "p=P[++]",  # 33: jump
    "S[S[length]-2]=S[S[length]-2]*S[pop]()",  # 34: mul
    "t0=P[++];",  # 35: je
    "S[S[length]-2]=S[S[length]-2]>S[pop]()",  # 36: ge
    "S[S[length]-2]=S[S[length]-2]>>S[pop]()",  # 37: rshift
    "S[S[length]-2]=S[S[length]-2]%S[pop]()",  # 38: mod
    "t0=S[pop]();S[push](deletet0[0][t0[1]])",  # 39: delattr
    "S[push](!1)",  # 40: false
    "S[S[length]-1]=window[S[S[length]-1]]",  # 41: get_global
    "S[S[length]-2]=S[S[length]-2]|S[pop]()",  # 42: bitor
    "S[S[length]-2]=S[S[length]-2]-S[pop]()",  # 43: sub
    "S[S[length]-2]=S[S[length]-2]^S[pop]()",  # 44: xor
    "t0=S[pop]();S[push]([S[S[pop]()][0],t0])",  # 45: grobj
    "t0=P[++];t1=t0?(S[slice](-t0)):([]);S[length]-=t0;t1[unshift](null);t0=S[pop]();S[push](t2(t0[0][t0[1]],t1))",  # 46: new_attr
    "S[push](!0)",  # 47: true
    "S[push](S[S[pop]()[0]][0])",  # 48: getobj2
    "S[S[length]-2]=S[S[length]-2]&S[pop]()",  # 49: bitand
    "S[S[length]-2]=S[S[length]-2]>>>S[pop]()",  # 50: urshift
    "S[length]=P[++]",  # 51: realloc
    ";t1=[];for in;S[push](t1)",  # 52: tolist
    "S[S[length]-2]=S[S[length]-2]/S[pop]()",  # 53: div
    "t0=S[pop]();t1=S[pop]();S[push]([t1[0][t1[1]],t0])",  # 54: grgetattr
    "S[S[length]-2]=S[S[length]-2]<<S[pop]()",  # 55: lshift
    "S[push](null)",  # 56: null
    "S[S[length]-1]+=String[fromCharCode](P[++])",  # 57: concat
)

OP_FEATS: Tuple[str, ...] = (
    "2a6add49d812b23c1518c5b129b945f8",  # 0: getattr -- t0=S[pop]();S[push](t0[0][t0[1]])
    "2c64a078cb8c4b856fdc70a609852c84",  # 1: inst -- S[push](P[++])
    "22baa62b15474dc170105ea16907be4f",  # 2: stepout -- t0[pop]()
    "a0d2ef60799df6195af8233faf1d4405",  # 3: geq -- S[S[length]-2]=S[S[length]-2]>=S[pop]()
    "821662fd6eed2bc7baf4ec9cf305ed3d",  # 4: copy -- S[push](S[S[length]-1])
    "86bfa469c728aef498dc0b31acca50d5",  # 5: inv -- S[push](!S[pop]())
    "a171259d3583f1d528c527cca37181c6",  # 6: arr_popleft -- S[S[length]-1][length]?(S[push](S[S[length]-1][shift](),!0)):(S[push](undefined,!1))
    "f4fb163d6ce50af6f20ceee6ba1b2e68",  # 7: grwinattr -- S[push]([window,S[pop]()])
    "36daeb76f0369182d47bc0854cd62f3e",  # 8: zstr -- S[push]('')
    "7861d746f3115dc52985788bad85f9f4",  # 9: clear -- t0=null
    "d5582f0d77825e3dd4b5de1b58c4367c",  # 10: eq -- S[S[length]-2]=S[S[length]-2]==S[pop]()
    "cac49f38e8d51bbe86aa5b8d7784b1d3",  # 11: vm_factory -- for;for;S[push](fun t0(){t1=t2[slice](0);t1[0]=[];t1[1]=[arguments];t1[2]=[t0];for;return __TENCENT_CHAOS_VM(t3,P,window,t1,t4,t5,t6,t7)})
    "85aeeab3938f54b19b45f3e95802c185",  # 12: assign -- S[S[length]-1]=P[++]
    "46be5ad0b74da7c1025e229ee1b86443",  # 13: typeof -- S[push](typeofS[pop]())
    "e6b094bc7d2c7092193723e0765c5848",  # 14: outcall -- t0=P[++];t1=t0?(S[slice](-t0)):([]);S[length]-=t0;t0=S[pop]();S[push](t0[0][t0[1]][apply](t0[0],t1))
    "a3dff4b562fdd065d4deace770c3d90e",  # 15: new -- t0=P[++];t1=t0?(S[slice](-t0)):([]);S[length]-=t0;t1[unshift](null);S[push](t2(S[pop](),t1))
    "19d1047281ae4901d0e08885458ceb5a",  # 16: inst_arr -- S[push]([P[++]])
    "e6803eb42dc05fc3e04283902865287c",  # 17: stop -- return !0
    "830b7a2b9fc1439b0358a00b20f229b2",  # 18: swap -- t0=P[++];t1=S[S[length]-2-t0];S[S[length]-2-t0]=S[pop]();S[push](t1)
    "854175af0e5ea31a14afd3b34a8faa80",  # 19: check_err -- return !!t0
    "2732918292df330ac7462015dff8969c",  # 20: throw -- throw S[S[length]-1]
    "d378d1594b18890e237b5d472818e309",  # 21: contains -- S[S[length]-2]=S[S[length]-2]inS[pop]()
    "c0d603b7a66da4e8d47907a2c11d4e7a",  # 22: setattr -- t0=S[S[length]-2];t0[0][t0[1]]=S[S[length]-1]
    "35bbb1a74b0380e46a199abe999bf303",  # 23: add -- S[S[length]-2]=S[S[length]-2]+S[pop]()
    "517f0463eba56f88b271acfbdda3c2f7",  # 24: n2list -- t0=P[++];S[t0]=S[t0]===undefined?([]):(S[t0])
    "c2b8e8732ecf925e116f1017a4fcfebf",  # 25: chobj -- S[S[S[length]-2][0]][0]=S[S[length]-1]
    "acaa0c50323b6fd6e8b9b9395f4ad30b",  # 26: getobj -- S[push](S[P[++]][0])
    "9557e2616caac44899f6612e32fa5cd2",  # 27: refeq -- S[S[length]-2]=S[S[length]-2]===S[pop]()
    "beb84fc4281460ec6d7610dcf039878d",  # 28: stepin -- t0[push]([P[++],S[length],P[++]])
    "c6539592b26bb629ad989902aef7375a",  # 29: group -- S[push]([S[pop](),S[pop]()][reverse]())
    "2e98536e65b245063c106e192a0fe58e",  # 30: wincall -- t0=P[++];t1=t0?(S[slice](-t0)):([]);S[length]-=t0;S[push](S[pop]()[apply](window,t1))
    "dacd0c2abe15333ad9d5aaf9e550da71",  # 31: drop -- S[pop]()
    "7211294be669b58b0f3da4940a35dcce",  # 32: undefined -- S[push](undefined)
    "fb632ca1b5f01438ecbb31c2560a78d8",  # 33: jump -- p=P[++]
    "a14cc4c1bd40951d1052c2c4c8353d13",  # 34: mul -- S[S[length]-2]=S[S[length]-2]*S[pop]()
    "1cc5222162165718596063a8d52e9df0",  # 35: je -- t0=P[++];
    "ac70343d82c97644522ed31a98649989",  # 36: ge -- S[S[length]-2]=S[S[length]-2]>S[pop]()
    "e41fa5e46c2d94d4d7b54437e71f5862",  # 37: rshift -- S[S[length]-2]=S[S[length]-2]>>S[pop]()
    "9c7676e1872be2fb9bf02aaefa78e066",  # 38: mod -- S[S[length]-2]=S[S[length]-2]%S[pop]()
    "a62dbee713cff9689e8235aac0cb553e",  # 39: delattr -- t0=S[pop]();S[push](deletet0[0][t0[1]])
    "4509710e44dc7c0bae5b39ee74b188c5",  # 40: false -- S[push](!1)
    "57270c2716f715468eaf0429965cf123",  # 41: get_global -- S[S[length]-1]=window[S[S[length]-1]]
    "61663d46238a47351f4ff7e24326360c",  # 42: bitor -- S[S[length]-2]=S[S[length]-2]|S[pop]()
    "3b20fb198a1f87da243bf27aadb19805",  # 43: sub -- S[S[length]-2]=S[S[length]-2]-S[pop]()
    "9c28d03d5a01e0360e830168b47ec0da",  # 44: xor -- S[S[length]-2]=S[S[length]-2]^S[pop]()
    "1540b5872b82ef5c2f093958043b5c7f",  # 45: grobj -- t0=S[pop]();S[push]([S[S[pop]()][0],t0])
    "42e24082bd8f6b2d3e1e6c5dfb01f6f3",  # 46: new_attr -- t0=P[++];t1=t0?(S[slice](-t0)):([]);S[length]-=t0;t1[unshift](null);t0=S[pop]();S[push](t2(t0[0][t0[1]],t1))
    "a7c235198def717b198ceb39d993ede9",  # 47: true -- S[push](!0)
    "80db3dff6284dfb62b88c7629af22afd",  # 48: getobj2 -- S[push](S[S[pop]()[0]][0])
    "d2d4c0d054580286a463d79d0881644a",  # 49: bitand -- S[S[length]-2]=S[S[length]-2]&S[pop]()
    "e66f61b8e3792cb44c2ae0be71173d45",  # 50: urshift -- S[S[length]-2]=S[S[length]-2]>>>S[pop]()
    "0bbd3879b0867fa76722b7ca001cb338",  # 51: realloc -- S[length]=P[++]
    "09a2a080abcdc4d360f6bc5bd05d8639",  # 52: tolist -- ;t1=[];for in;S[push](t1)
    "af29f37ff067adb9398e5b9b42b8f7b7",  # 53: div -- S[S[length]-2]=S[S[length]-2]/S[pop]()
    "3e1299db7ebd033250a85059e176ed1c",  # 54: grgetattr -- t0=S[pop]();t1=S[pop]();S[push]([t1[0][t1[1]],t0])
    "c00fc6652cacebbf04dc3958a058150c",  # 55: lshift -- S[S[length]-2]=S[S[length]-2]<<S[pop]()
    "2598bc9255deafbb48adf287d5d3b12a",  # 56: null -- S[push](null)
    "13274e03e106918b096bc5fd4c5423ba",  # 57: concat -- S[S[length]-1]+=String[fromCharCode](P[++])
)
# fmt: on
