# AUTO-GENERATED BY scripts/generate_opfeats.py
# Sources:
#  - (funarr) js\template\funarr_pattern.js
#  - (switch) js\template\switch_pattern.js
# Do not edit manually.

# fmt: off

# ============ funarr VM (58 ops) ============
FUNARR_OP_COUNT: int = 58

FUNARR_OP_NAMES: tuple[str, ...] = (
    "getattr",
    "immediate",
    "stepout",
    "geq",
    "copy",
    "inv",
    "arr_popleft",
    "grwinattr",
    "zstr",
    "clear",
    "eq",
    "vm_factory",
    "assign",
    "typeof",
    "outcall",
    "new",
    "inst_arr",
    "stop",
    "swap",
    "check_err",
    "throw",
    "contains",
    "setattr",
    "add",
    "n2list",
    "chobj",
    "getobj",
    "refeq",
    "stepin",
    "group",
    "wincall",
    "drop",
    "undefined",
    "jump",
    "mul",
    "je",
    "ge",
    "rshift",
    "mod",
    "delattr",
    "false",
    "get_global",
    "bitor",
    "sub",
    "xor",
    "grobj",
    "new_attr",
    "true",
    "getobj2",
    "bitand",
    "urshift",
    "realloc",
    "tolist",
    "div",
    "grgetattr",
    "lshift",
    "null",
    "concat",
)

FUNARR_OP_SYNTAX: tuple[str, ...] = (
    "t0=S[pop]();S[push](t0[0][t0[1]])",  # 0: getattr
    "S[push](P[++])",  # 1: immediate
    "t0[pop]()",  # 2: stepout
    "S[S[length]-2]=S[S[length]-2]>=S[pop]()",  # 3: geq
    "S[push](S[S[length]-1])",  # 4: copy
    "S[push](!S[pop]())",  # 5: inv
    "S[S[length]-1][length]?(S[push](S[S[length]-1][shift](),!0)):(S[push](undefined,!1))",  # 6: arr_popleft
    "S[push]([window,S[pop]()])",  # 7: grwinattr
    "S[push]('')",  # 8: zstr
    "t0=null",  # 9: clear
    "S[S[length]-2]=S[S[length]-2]==S[pop]()",  # 10: eq
    "for;for;S[push](fun t0(){t1=t2[slice](0);t1[0]=[];t1[1]=[arguments];t1[2]=[t0];for;return __TENCENT_CHAOS_VM(t3,P,window,t1,t4,t5,t6,t7)})",  # 11: vm_factory
    "S[S[length]-1]=P[++]",  # 12: assign
    "S[push](typeofS[pop]())",  # 13: typeof
    "t0=P[++];t1=t0?(S[slice](-t0)):([]);S[length]-=t0;t0=S[pop]();S[push](t0[0][t0[1]][apply](t0[0],t1))",  # 14: outcall
    "t0=P[++];t1=t0?(S[slice](-t0)):([]);S[length]-=t0;t1[unshift](null);S[push](t2(S[pop](),t1))",  # 15: new
    "S[push]([P[++]])",  # 16: inst_arr
    "return !0",  # 17: stop
    "t0=P[++];t1=S[S[length]-2-t0];S[S[length]-2-t0]=S[pop]();S[push](t1)",  # 18: swap
    "return !!t0",  # 19: check_err
    "throw S[S[length]-1]",  # 20: throw
    "S[S[length]-2]=S[S[length]-2]inS[pop]()",  # 21: contains
    "t0=S[S[length]-2];t0[0][t0[1]]=S[S[length]-1]",  # 22: setattr
    "S[S[length]-2]=S[S[length]-2]+S[pop]()",  # 23: add
    "t0=P[++];S[t0]=S[t0]===undefined?([]):(S[t0])",  # 24: n2list
    "S[S[S[length]-2][0]][0]=S[S[length]-1]",  # 25: chobj
    "S[push](S[P[++]][0])",  # 26: getobj
    "S[S[length]-2]=S[S[length]-2]===S[pop]()",  # 27: refeq
    "t0[push]([P[++],S[length],P[++]])",  # 28: stepin
    "S[push]([S[pop](),S[pop]()][reverse]())",  # 29: group
    "t0=P[++];t1=t0?(S[slice](-t0)):([]);S[length]-=t0;S[push](S[pop]()[apply](window,t1))",  # 30: wincall
    "S[pop]()",  # 31: drop
    "S[push](undefined)",  # 32: undefined
    "p=P[++]",  # 33: jump
    "S[S[length]-2]=S[S[length]-2]*S[pop]()",  # 34: mul
    "t0=P[++];",  # 35: je
    "S[S[length]-2]=S[S[length]-2]>S[pop]()",  # 36: ge
    "S[S[length]-2]=S[S[length]-2]>>S[pop]()",  # 37: rshift
    "S[S[length]-2]=S[S[length]-2]%S[pop]()",  # 38: mod
    "t0=S[pop]();S[push](deletet0[0][t0[1]])",  # 39: delattr
    "S[push](!1)",  # 40: false
    "S[S[length]-1]=window[S[S[length]-1]]",  # 41: get_global
    "S[S[length]-2]=S[S[length]-2]|S[pop]()",  # 42: bitor
    "S[S[length]-2]=S[S[length]-2]-S[pop]()",  # 43: sub
    "S[S[length]-2]=S[S[length]-2]^S[pop]()",  # 44: xor
    "t0=S[pop]();S[push]([S[S[pop]()][0],t0])",  # 45: grobj
    "t0=P[++];t1=t0?(S[slice](-t0)):([]);S[length]-=t0;t1[unshift](null);t0=S[pop]();S[push](t2(t0[0][t0[1]],t1))",  # 46: new_attr
    "S[push](!0)",  # 47: true
    "S[push](S[S[pop]()[0]][0])",  # 48: getobj2
    "S[S[length]-2]=S[S[length]-2]&S[pop]()",  # 49: bitand
    "S[S[length]-2]=S[S[length]-2]>>>S[pop]()",  # 50: urshift
    "S[length]=P[++]",  # 51: realloc
    ";t1=[];for in;S[push](t1)",  # 52: tolist
    "S[S[length]-2]=S[S[length]-2]/S[pop]()",  # 53: div
    "t0=S[pop]();t1=S[pop]();S[push]([t1[0][t1[1]],t0])",  # 54: grgetattr
    "S[S[length]-2]=S[S[length]-2]<<S[pop]()",  # 55: lshift
    "S[push](null)",  # 56: null
    "S[S[length]-1]+=String[fromCharCode](P[++])",  # 57: concat
)

FUNARR_OP_FEATS: tuple[str, ...] = (
    "2a6add49d812b23c1518c5b129b945f8",  # 0: getattr
    "2c64a078cb8c4b856fdc70a609852c84",  # 1: immediate
    "22baa62b15474dc170105ea16907be4f",  # 2: stepout
    "a0d2ef60799df6195af8233faf1d4405",  # 3: geq
    "821662fd6eed2bc7baf4ec9cf305ed3d",  # 4: copy
    "86bfa469c728aef498dc0b31acca50d5",  # 5: inv
    "a171259d3583f1d528c527cca37181c6",  # 6: arr_popleft
    "f4fb163d6ce50af6f20ceee6ba1b2e68",  # 7: grwinattr
    "36daeb76f0369182d47bc0854cd62f3e",  # 8: zstr
    "7861d746f3115dc52985788bad85f9f4",  # 9: clear
    "d5582f0d77825e3dd4b5de1b58c4367c",  # 10: eq
    "cac49f38e8d51bbe86aa5b8d7784b1d3",  # 11: vm_factory
    "85aeeab3938f54b19b45f3e95802c185",  # 12: assign
    "46be5ad0b74da7c1025e229ee1b86443",  # 13: typeof
    "e6b094bc7d2c7092193723e0765c5848",  # 14: outcall
    "a3dff4b562fdd065d4deace770c3d90e",  # 15: new
    "19d1047281ae4901d0e08885458ceb5a",  # 16: inst_arr
    "e6803eb42dc05fc3e04283902865287c",  # 17: stop
    "830b7a2b9fc1439b0358a00b20f229b2",  # 18: swap
    "854175af0e5ea31a14afd3b34a8faa80",  # 19: check_err
    "2732918292df330ac7462015dff8969c",  # 20: throw
    "d378d1594b18890e237b5d472818e309",  # 21: contains
    "c0d603b7a66da4e8d47907a2c11d4e7a",  # 22: setattr
    "35bbb1a74b0380e46a199abe999bf303",  # 23: add
    "517f0463eba56f88b271acfbdda3c2f7",  # 24: n2list
    "c2b8e8732ecf925e116f1017a4fcfebf",  # 25: chobj
    "acaa0c50323b6fd6e8b9b9395f4ad30b",  # 26: getobj
    "9557e2616caac44899f6612e32fa5cd2",  # 27: refeq
    "beb84fc4281460ec6d7610dcf039878d",  # 28: stepin
    "c6539592b26bb629ad989902aef7375a",  # 29: group
    "2e98536e65b245063c106e192a0fe58e",  # 30: wincall
    "dacd0c2abe15333ad9d5aaf9e550da71",  # 31: drop
    "7211294be669b58b0f3da4940a35dcce",  # 32: undefined
    "fb632ca1b5f01438ecbb31c2560a78d8",  # 33: jump
    "a14cc4c1bd40951d1052c2c4c8353d13",  # 34: mul
    "1cc5222162165718596063a8d52e9df0",  # 35: je
    "ac70343d82c97644522ed31a98649989",  # 36: ge
    "e41fa5e46c2d94d4d7b54437e71f5862",  # 37: rshift
    "9c7676e1872be2fb9bf02aaefa78e066",  # 38: mod
    "a62dbee713cff9689e8235aac0cb553e",  # 39: delattr
    "4509710e44dc7c0bae5b39ee74b188c5",  # 40: false
    "57270c2716f715468eaf0429965cf123",  # 41: get_global
    "61663d46238a47351f4ff7e24326360c",  # 42: bitor
    "3b20fb198a1f87da243bf27aadb19805",  # 43: sub
    "9c28d03d5a01e0360e830168b47ec0da",  # 44: xor
    "1540b5872b82ef5c2f093958043b5c7f",  # 45: grobj
    "42e24082bd8f6b2d3e1e6c5dfb01f6f3",  # 46: new_attr
    "a7c235198def717b198ceb39d993ede9",  # 47: true
    "80db3dff6284dfb62b88c7629af22afd",  # 48: getobj2
    "d2d4c0d054580286a463d79d0881644a",  # 49: bitand
    "e66f61b8e3792cb44c2ae0be71173d45",  # 50: urshift
    "0bbd3879b0867fa76722b7ca001cb338",  # 51: realloc
    "09a2a080abcdc4d360f6bc5bd05d8639",  # 52: tolist
    "af29f37ff067adb9398e5b9b42b8f7b7",  # 53: div
    "3e1299db7ebd033250a85059e176ed1c",  # 54: grgetattr
    "c00fc6652cacebbf04dc3958a058150c",  # 55: lshift
    "2598bc9255deafbb48adf287d5d3b12a",  # 56: null
    "13274e03e106918b096bc5fd4c5423ba",  # 57: concat
)

# ============ switch VM (96 ops) ============
SWITCH_OP_COUNT: int = 96

SWITCH_OP_NAMES: tuple[str, ...] = (
    "op_0_add_reg",
    "op_1_jcond",
    "op_2_to_num",
    "op_3_push_ret",
    "op_4_to_num_unary",
    "op_5_add_imm",
    "op_6_eq_imm",
    "op_7_getprop_imm",
    "op_8_ushr_imm",
    "op_9_new_1",
    "op_10_throw",
    "op_11_setprop_ret",
    "op_12_call_0",
    "op_13_getprop_call",
    "op_14_gt_reg",
    "op_15_eq_reg",
    "op_16_setprop2",
    "op_17_ret",
    "op_18_getprop2",
    "op_19_catch_setup",
    "op_20_call_3",
    "op_21_str_char2",
    "op_22_typeof",
    "op_23_lt_reg",
    "op_24_sar_imm",
    "op_25_push_catch",
    "op_26_mov",
    "op_27_neg",
    "op_28_str_init_char",
    "op_29_pop_catch",
    "op_30_or_imm",
    "op_31_mul_reg",
    "op_32_shl_reg",
    "op_33_or_reg",
    "op_34_getprop_idx",
    "op_35_in",
    "op_36_not",
    "op_37_str_init",
    "op_38_setprop2_ctx",
    "op_39_call_1",
    "op_40_array_iter",
    "op_41_call_1_save",
    "op_42_str_char_set",
    "op_43_str_char_set_clr",
    "op_44_str_char_obj",
    "op_45_ge_imm",
    "op_46_load_exc",
    "op_47_str_char_prop",
    "op_48_load_imm",
    "op_49_inc_copy",
    "op_50_setprop_ret_ctx",
    "op_51_load_ctx",
    "op_52_str_char_prop2",
    "op_53_seq_imm",
    "op_54_div_reg",
    "op_55_mod_reg",
    "op_56_keys",
    "op_57_func_create",
    "op_58_dup2",
    "op_59_and_imm",
    "op_60_sub_imm_rev",
    "op_61_sub_reg",
    "op_62_new_0",
    "op_63_call_3_ctx",
    "op_64_str_char3",
    "op_65_call_1_ctx",
    "op_66_load_null",
    "op_67_seq_reg",
    "op_68_apply",
    "op_69_setprop_imm",
    "op_70_str_func_prop",
    "op_71_shl_imm",
    "op_72_sar_reg",
    "op_73_str_char",
    "op_74_delprop",
    "op_75_func_create2",
    "op_76_jmp",
    "op_77_func_method",
    "op_78_call_2",
    "op_79_sub_imm",
    "op_80_load_call",
    "op_81_gt_imm",
    "op_82_call_2_dyn",
    "op_83_pre_inc",
    "op_84_setprop_dyn",
    "op_85_array_new",
    "op_86_obj_new",
    "op_87_xor_reg",
    "op_88_lt_imm",
    "op_89_new_2",
    "op_90_setprop_get",
    "op_91_getprop_dyn",
    "op_92_pre_dec",
    "op_93_ret_ctx",
    "op_94_call_2_ctx",
    "op_95_le_imm",
)

SWITCH_OP_SYNTAX: tuple[str, ...] = (
    "R[o[^++]]=R[o[^++]]+R[o[^++]];",  # 0: op_0_add_reg
    "K+=R[o[^++]]?(o[^++]):(o[^++;^++]);",  # 1: op_1_jcond
    "R[o[^++]]='bigint'==typeofR[o[K+1]]?(R[o[^++]]):(R[o[^++]]-0);",  # 2: op_2_to_num
    "C[push](K+o[^++]);",  # 3: op_3_push_ret
    "R[o[^++]]=+R[o[^++]];",  # 4: op_4_to_num_unary
    "R[o[^++]]=R[o[^++]]+o[^++];",  # 5: op_5_add_imm
    "R[o[^++]]=R[o[^++]]==o[^++];",  # 6: op_6_eq_imm
    "R[o[^++]]=R[o[^++]][o[^++]];",  # 7: op_7_getprop_imm
    "R[o[^++]]=R[o[^++]]>>>o[^++];",  # 8: op_8_ushr_imm
    "R[o[^++]]=new R[o[^++]]();",  # 9: op_9_new_1
    "throw R[o[^++]];",  # 10: op_10_throw
    "R[o[^++]][o[^++]]=R[o[^++]];return R[o[^++]];",  # 11: op_11_setprop_ret
    "R[o[^++]]=R[o[^++]][call](Q);",  # 12: op_12_call_0
    "R[o[^++]]=R[o[^++]][R[o[^++]]];R[o[^++]]=R[o[^++]][call](R[o[^++]],R[o[^++]]);",  # 13: op_13_getprop_call
    "R[o[^++]]=R[o[^++]]>R[o[^++]];",  # 14: op_14_gt_reg
    "R[o[^++]]=R[o[^++]]==R[o[^++]];",  # 15: op_15_eq_reg
    "R[o[^++]]=R[o[^++]];R[o[^++]][R[o[^++]]]=R[o[^++]];",  # 16: op_16_setprop2
    "return R[o[^++]];",  # 17: op_17_ret
    "R[o[^++]]=R[o[^++]][o[^++]];R[o[^++]]=R[o[^++]][o[^++]];",  # 18: op_18_getprop2
    "R[o[^++]]=U;R[o[^++]]=R[o[^++]];C[push](K+o[^++]);",  # 19: op_19_catch_setup
    "R[o[^++]]=R[o[^++]][call](R[o[^++]],R[o[^++]],R[o[^++]],R[o[^++]]);",  # 20: op_20_call_3
    "R[o[^++]]+=String[fromCharCode](o[^++]);R[o[^++]]+=String[fromCharCode](o[^++]);",  # 21: op_21_str_char2
    "R[o[^++]]=typeofR[o[^++]];",  # 22: op_22_typeof
    "R[o[^++]]=R[o[^++]]<R[o[^++]];",  # 23: op_23_lt_reg
    "R[o[^++]]=R[o[^++]]>>o[^++];",  # 24: op_24_sar_imm
    "R[o[^++]]=R[o[^++]];C[push](K+o[^++]);",  # 25: op_25_push_catch
    "R[o[^++]]=R[o[^++]];",  # 26: op_26_mov
    "R[o[^++]]=-R[o[^++]];",  # 27: op_27_neg
    "R[o[^++]]='';R[o[^++]]+=String[fromCharCode](o[^++]);",  # 28: op_28_str_init_char
    "C[pop]();",  # 29: op_29_pop_catch
    "R[o[^++]]=R[o[^++]]|o[^++];",  # 30: op_30_or_imm
    "R[o[^++]]=R[o[^++]]*R[o[^++]];",  # 31: op_31_mul_reg
    "R[o[^++]]=R[o[^++]]<<R[o[^++]];",  # 32: op_32_shl_reg
    "R[o[^++]]=R[o[^++]]|R[o[^++]];",  # 33: op_33_or_reg
    "R[o[^++]]=R[o[^++]][R[o[^++]]];R[o[^++]]=o[^++];",  # 34: op_34_getprop_idx
    "R[o[^++]]=R[o[^++]]inR[o[^++]];",  # 35: op_35_in
    "R[o[^++]]=!R[o[^++]];",  # 36: op_36_not
    "R[o[^++]]='';",  # 37: op_37_str_init
    "R[o[^++]][R[o[^++]]]=R[o[^++]];R[o[^++]][R[o[^++]]]=R[o[^++]];R[o[^++]]=Q;",  # 38: op_38_setprop2_ctx
    "R[o[^++]]=R[o[^++]][call](R[o[^++]]);",  # 39: op_39_call_1
    "w=R[o[^++]];;",  # 40: op_40_array_iter
    "R[o[^++]]=R[o[^++]][call](Q,R[o[^++]]);R[o[^++]]=R[o[^++]];",  # 41: op_41_call_1_save
    "R[o[^++]]+=String[fromCharCode](o[^++]);R[o[^++]][o[^++]]=R[o[^++]];",  # 42: op_42_str_char_set
    "R[o[^++]]+=String[fromCharCode](o[^++]);R[o[^++]][o[^++]]=R[o[^++]];R[o[^++]]='';",  # 43: op_43_str_char_set_clr
    "R[o[^++]]+=String[fromCharCode](o[^++]);R[o[^++]]=;R[o[^++]]='';",  # 44: op_44_str_char_obj
    "R[o[^++]]=R[o[^++]]>=o[^++];",  # 45: op_45_ge_imm
    "R[o[^++]]=U;",  # 46: op_46_load_exc
    "R[o[^++]]=R[o[^++]][R[o[^++]]];R[o[^++]]='';R[o[^++]]+=String[fromCharCode](o[^++]);",  # 47: op_47_str_char_prop
    "R[o[^++]]=o[^++];",  # 48: op_48_load_imm
    "R[o[^++]]='bigint'==typeofR[o[K+1]]?(R[o[^++]]):(R[o[^++]]-0);R[o[^++]]=^++;R[o[^++]]=R[o[^++]];",  # 49: op_49_inc_copy
    "R[o[^++]][R[o[^++]]]=R[o[^++]];R[o[^++]]=Q;return R[o[^++]];",  # 50: op_50_setprop_ret_ctx
    "R[o[^++]]=Q;",  # 51: op_51_load_ctx
    "R[o[^++]]+=String[fromCharCode](o[^++]);R[o[^++]]=R[o[^++]][R[o[^++]]];",  # 52: op_52_str_char_prop2
    "R[o[^++]]=R[o[^++]]===o[^++];",  # 53: op_53_seq_imm
    "R[o[^++]]=R[o[^++]]/R[o[^++]];",  # 54: op_54_div_reg
    "R[o[^++]]=R[o[^++]]%R[o[^++]];",  # 55: op_55_mod_reg
    "w=[];for in;R[o[^++]]=w;",  # 56: op_56_keys
    "w=[];for;R[o[^++]]=S(K+o[^++],w,Y,I,G);;",  # 57: op_57_func_create
    "R[o[^++]]=R[o[^++]];R[o[^++]]=R[o[^++]];",  # 58: op_58_dup2
    "R[o[^++]]=R[o[^++]]&o[^++];",  # 59: op_59_and_imm
    "R[o[^++]]=o[^++]-R[o[^++]];",  # 60: op_60_sub_imm_rev
    "R[o[^++]]=R[o[^++]]-R[o[^++]];",  # 61: op_61_sub_reg
    "R[o[^++]]=new R[o[^++]]();",  # 62: op_62_new_0
    "R[o[^++]]=R[o[^++]][call](Q,R[o[^++]],R[o[^++]],R[o[^++]]);",  # 63: op_63_call_3_ctx
    "R[o[^++]]+=String[fromCharCode](o[^++]);R[o[^++]]+=String[fromCharCode](o[^++]);R[o[^++]]+=String[fromCharCode](o[^++]);",  # 64: op_64_str_char3
    "R[o[^++]]=R[o[^++]][call](Q,R[o[^++]]);",  # 65: op_65_call_1_ctx
    "R[o[^++]]=null;",  # 66: op_66_load_null
    "R[o[^++]]=R[o[^++]]===R[o[^++]];",  # 67: op_67_seq_reg
    "w=[];for;R[o[^++]]=R[o[^++]][apply](R[o[^++]],w);",  # 68: op_68_apply
    "R[o[^++]][o[^++]]=R[o[^++]];",  # 69: op_69_setprop_imm
    "R[o[^++]]+=String[fromCharCode](o[^++]);w=[];for;R[o[^++]]=S(K+o[^++],w,Y,I,G);;R[o[^++]][R[o[^++]]]=R[o[^++]];",  # 70: op_70_str_func_prop
    "R[o[^++]]=R[o[^++]]<<o[^++];",  # 71: op_71_shl_imm
    "R[o[^++]]=R[o[^++]]>>R[o[^++]];",  # 72: op_72_sar_reg
    "R[o[^++]]+=String[fromCharCode](o[^++]);",  # 73: op_73_str_char
    "R[o[^++]]=deleteR[o[^++]][R[o[^++]]];",  # 74: op_74_delprop
    "w=[];for;R[o[^++]]=S(K+o[^++],w,Y,I,G);;R[o[^++]][o[^++]]=R[o[^++]];w=[];for;R[o[^++]]=S(K+o[^++],w,Y,I,G);;",  # 75: op_75_func_create2
    "K+=o[^++];",  # 76: op_76_jmp
    "R[o[^++]][o[^++]]=R[o[^++]];w=[];for;R[o[^++]]=S(K+o[^++],w,Y,I,G);;R[o[^++]][o[^++]]=R[o[^++]];",  # 77: op_77_func_method
    "R[o[^++]]=R[o[^++]][call](R[o[^++]],R[o[^++]],R[o[^++]]);",  # 78: op_78_call_2
    "R[o[^++]]=R[o[^++]]-o[^++];",  # 79: op_79_sub_imm
    "R[o[^++]]=o[^++];R[o[^++]]=R[o[^++]][call](Q,R[o[^++]]);R[o[^++]]=R[o[^++]];",  # 80: op_80_load_call
    "R[o[^++]]=R[o[^++]]>o[^++];",  # 81: op_81_gt_imm
    "R[o[^++]]=R[o[^++]][call](R[o[^++]],R[o[^++]]);",  # 82: op_82_call_2_dyn
    "R[o[^++]]=^++;",  # 83: op_83_pre_inc
    "R[o[^++]][R[o[^++]]]=R[o[^++]];",  # 84: op_84_setprop_dyn
    "R[o[^++]]=Array(o[^++]);",  # 85: op_85_array_new
    "R[o[^++]]=;",  # 86: op_86_obj_new
    "R[o[^++]]=R[o[^++]]^R[o[^++]];",  # 87: op_87_xor_reg
    "R[o[^++]]=R[o[^++]]<o[^++];",  # 88: op_88_lt_imm
    "R[o[^++]]=new R[o[^++]]();",  # 89: op_89_new_2
    "R[o[^++]][R[o[^++]]]=R[o[^++]];R[o[^++]]=R[o[^++]][R[o[^++]]];R[o[^++]]=o[^++];",  # 90: op_90_setprop_get
    "R[o[^++]]=R[o[^++]][R[o[^++]]];",  # 91: op_91_getprop_dyn
    "R[o[^++]]=^--;",  # 92: op_92_pre_dec
    "R[o[^++]]=Q;return R[o[^++]];",  # 93: op_93_ret_ctx
    "R[o[^++]]=R[o[^++]][call](Q,R[o[^++]],R[o[^++]]);",  # 94: op_94_call_2_ctx
    "R[o[^++]]=R[o[^++]]<=o[^++];",  # 95: op_95_le_imm
)

SWITCH_OP_FEATS: tuple[str, ...] = (
    "66a31c709b8469311d072f534b9d6e68",  # 0: op_0_add_reg
    "5ecc08f1ba8326e10af9c6d6ab320c73",  # 1: op_1_jcond
    "4e8610aa10731e87d168a44e17ef701b",  # 2: op_2_to_num
    "0449ff687d0bd36cb90762850e3712bf",  # 3: op_3_push_ret
    "e8bab1feaaa36c01b00c4cea08ca62e4",  # 4: op_4_to_num_unary
    "e81fa63ca089c5fd31a18831a4ce19d2",  # 5: op_5_add_imm
    "032acf1a9f283ef642c8c1bc029b8521",  # 6: op_6_eq_imm
    "37c01b863a6156bddffde924fbe4d54e",  # 7: op_7_getprop_imm
    "5b7c42f48afd99ed6b8ed5b5a7c9eb15",  # 8: op_8_ushr_imm
    "402af1be755b608220943ffe1ed3df25",  # 9: op_9_new_1
    "3dfb0c9f87d936cc5f60c293c34c262c",  # 10: op_10_throw
    "5cbcc529e1c418d64e8fc07acfeaa5a0",  # 11: op_11_setprop_ret
    "d6b090fd71d1d8af8feea7319feea7ee",  # 12: op_12_call_0
    "f3c47c3d14f046018a6b171452bfaffd",  # 13: op_13_getprop_call
    "614f11d9e48a6116a06a0cfb2f8c8533",  # 14: op_14_gt_reg
    "6a78ac327de94a5bc115d0cb30696ffe",  # 15: op_15_eq_reg
    "aa3ec94e2240bd72848a02508793459c",  # 16: op_16_setprop2
    "c822ed5c17ab959524cfa4a807907a68",  # 17: op_17_ret
    "0746ae4c7124026b403ebdfe4acbbada",  # 18: op_18_getprop2
    "fe36e995c181b44a03678c4779200b6b",  # 19: op_19_catch_setup
    "cdc1b67d74452b0f0bc91a51ba5bd00e",  # 20: op_20_call_3
    "ddb8c99d56fd758164a0b356c69c0e80",  # 21: op_21_str_char2
    "71128c2ec6b9f8a1f5f7dbd47e8a9a20",  # 22: op_22_typeof
    "6ca5645c991fbe1fcbfe2b249ee0012e",  # 23: op_23_lt_reg
    "984a9c69a541ccea9a2cdc0e296e98d7",  # 24: op_24_sar_imm
    "ebbece07c0b156e4bbae9bb2cb85a3f3",  # 25: op_25_push_catch
    "a2fcb8a956dfb954ccb6399010d61d80",  # 26: op_26_mov
    "e28661e9057e176ddd73d9d2e2a05093",  # 27: op_27_neg
    "0cc49d836503b0ddf50e9feca121761d",  # 28: op_28_str_init_char
    "dc848ae1144459565f885f8d6cf658ae",  # 29: op_29_pop_catch
    "b3bd8514a69a1e6565e015872ccd8527",  # 30: op_30_or_imm
    "beb964188a53a0baaaea5e71403b06a8",  # 31: op_31_mul_reg
    "9b93b7e9f94e4270d493cd02fadd3fae",  # 32: op_32_shl_reg
    "5f329db03b9f23bd448a84277dd462b5",  # 33: op_33_or_reg
    "8c0fdc931cc975ecb9be84322b204d4d",  # 34: op_34_getprop_idx
    "dca134d575435587f88df624ca274e27",  # 35: op_35_in
    "9fb7476e5398a8164f6ff44277b8fb14",  # 36: op_36_not
    "5aa2451eca1fc7aa41fec8721a249363",  # 37: op_37_str_init
    "e4a5c453a3315ca202ddc66c53d86e16",  # 38: op_38_setprop2_ctx
    "4a32f164197a627c05cdefa835e3520e",  # 39: op_39_call_1
    "a3c1f9517d918a694dfcb85811b69cf4",  # 40: op_40_array_iter
    "2036d83665b44d6a437fdf47ffdf8f71",  # 41: op_41_call_1_save
    "03069ab1c40e3ef7d09e43a294b6954d",  # 42: op_42_str_char_set
    "0be9f57c41acc0e9eb8361aa411584d6",  # 43: op_43_str_char_set_clr
    "1ee661b494c1e3486def5d87a5afd547",  # 44: op_44_str_char_obj
    "5fe7020578190763f446914833bcb5b2",  # 45: op_45_ge_imm
    "2525fdc0e47aac3c178bb8d5e1d46fea",  # 46: op_46_load_exc
    "533c435f270cf01427075094b83e01cc",  # 47: op_47_str_char_prop
    "31e8d49b43bbabbe574e417f88c9680c",  # 48: op_48_load_imm
    "34908e71e0026cc14f02e52c5b0db76e",  # 49: op_49_inc_copy
    "18b6d6b29a9c26bf1d1556fa1854d9d0",  # 50: op_50_setprop_ret_ctx
    "f573320c21d8c3d577120dff5f6cf0d4",  # 51: op_51_load_ctx
    "585bab72147602c449c362c5c2aaf26a",  # 52: op_52_str_char_prop2
    "b3d08c2b24cdb3e579fee1bb5a5c0c20",  # 53: op_53_seq_imm
    "6a2682fe4cfc4d706671743e4ec28eed",  # 54: op_54_div_reg
    "2b4908efd8bdc3ba2b00ae65afac1318",  # 55: op_55_mod_reg
    "acb72e4e45749a73be0db5f628d4b1d7",  # 56: op_56_keys
    "e9f9f945bc1c63c88eeb3b4dfb906405",  # 57: op_57_func_create
    "4e5ec5af96ddefde5d86c2d105cd5816",  # 58: op_58_dup2
    "af0976e1e2cd130947fe4e6f70c272f9",  # 59: op_59_and_imm
    "16d0bae608eb749e3ef6d6a0ab4cf658",  # 60: op_60_sub_imm_rev
    "6bdc29d682fc0df5925076f7191742d0",  # 61: op_61_sub_reg
    "402af1be755b608220943ffe1ed3df25",  # 62: op_62_new_0
    "839d9ad98e80ae20aa6c63e00b84ee90",  # 63: op_63_call_3_ctx
    "cca7fe21ff78f1a355f2abc06501df51",  # 64: op_64_str_char3
    "71b5eae75deae4a84994f793f21f60b4",  # 65: op_65_call_1_ctx
    "7706bda2a976f4303cec745a119e69d2",  # 66: op_66_load_null
    "a5940e4f34671aac8b5343cbd3c79f40",  # 67: op_67_seq_reg
    "c15f24b95304cf9f2258101a6a2617c6",  # 68: op_68_apply
    "303c75aadb8cb222910dc6aa7253ae56",  # 69: op_69_setprop_imm
    "5ec7b45b21e757c836d03229858b9b0e",  # 70: op_70_str_func_prop
    "7e2229e649b207931119307795275588",  # 71: op_71_shl_imm
    "0660f53f391f166d6a1c836c22a77b07",  # 72: op_72_sar_reg
    "d26163c10471a63f07a2c81929b89c8c",  # 73: op_73_str_char
    "1ba1427f0205910645f9be104e10df2d",  # 74: op_74_delprop
    "29a1202d04e9d59492136a86b447c1cd",  # 75: op_75_func_create2
    "d6576ea6223139fb6718a782f49fcb3b",  # 76: op_76_jmp
    "f779fd7f4da9ecc79bdf758d14e4141a",  # 77: op_77_func_method
    "7ad15661b39f047afc86b5a2c842fc21",  # 78: op_78_call_2
    "1072ba343adc3d2bce2759fe3a614fd9",  # 79: op_79_sub_imm
    "04828a0d878c427fc47d1827643b06e6",  # 80: op_80_load_call
    "8c0f654a947b3fed3b560be305bee8ac",  # 81: op_81_gt_imm
    "5fc9a25e8f333f9718c25252fe539dd8",  # 82: op_82_call_2_dyn
    "80d00cd777288ade75f8ab43da925554",  # 83: op_83_pre_inc
    "d6e3c1ffe9f7da63c97a41a78ae50f81",  # 84: op_84_setprop_dyn
    "0103d2fd25219d95c23489c98316d422",  # 85: op_85_array_new
    "cc9eaf884af2751a35d081353fc90476",  # 86: op_86_obj_new
    "fc25799979e57affccbc9a52c72f8e6b",  # 87: op_87_xor_reg
    "76e7bf97a8718228eadecb5ec3ac9042",  # 88: op_88_lt_imm
    "402af1be755b608220943ffe1ed3df25",  # 89: op_89_new_2
    "23a0bab6db053c269bc3aa06af0f91e2",  # 90: op_90_setprop_get
    "3db6b9e235cf01ec3112d107b11c1454",  # 91: op_91_getprop_dyn
    "dc4237fba837cd19faba6244092bf3aa",  # 92: op_92_pre_dec
    "9266d19bded915e102d9d3c671f60d82",  # 93: op_93_ret_ctx
    "fbca2703a0d608e4253b58ff14198d01",  # 94: op_94_call_2_ctx
    "77d06360309a4fbf4f8cddd7f8eaaec0",  # 95: op_95_le_imm
)

# fmt: on
