#!/usr/bin/env python3
"""Generate opfeats.py from a ChaosVM JS snippet and the BuiltinOps implementation."""

from __future__ import annotations

import argparse
import ast
import sys
from collections import defaultdict
from hashlib import md5
from pathlib import Path

from pyjsparser import parse

from chaosvm.parse import path_get
from chaosvm.stxhash import syntax_hash

PROJECT_ROOT = Path(__file__).parent.parent
VM_PY_PATH = PROJECT_ROOT / "src" / "chaosvm" / "vm.py"


def extract_op_names(vm_py_path: Path = VM_PY_PATH) -> list[str]:
    """Parse vm.py and extract the ordered list of opcode method names from self.ops."""
    source = vm_py_path.read_text(encoding="utf-8")
    tree = ast.parse(source)

    for node in ast.walk(tree):
        if not isinstance(node, ast.ClassDef) or node.name != "BuiltinOps":
            continue
        for item in node.body:
            if isinstance(item, ast.FunctionDef) and item.name == "__init__":
                for stmt in item.body:
                    if (
                        isinstance(stmt, ast.Assign)
                        and len(stmt.targets) == 1
                        and isinstance(stmt.targets[0], ast.Attribute)
                        and stmt.targets[0].attr == "ops"
                        and isinstance(stmt.value, ast.List)
                    ):
                        names = []
                        for elt in stmt.value.elts:
                            if isinstance(elt, ast.Attribute) and elt.attr != "ops":
                                names.append(elt.attr)
                            else:
                                raise ValueError(
                                    f"Unexpected element in self.ops: {ast.dump(elt)}"
                                )
                        return names
    raise RuntimeError("Could not find self.ops list in BuiltinOps.__init__")


def extract_op_syntax(u_js_path: Path) -> list[str]:
    """Parse U.js and return the ordered list of syntax-hash strings for opcodes."""
    source = u_js_path.read_text(encoding="utf-8")
    ast_ = parse(source)

    G = dict(k="p", B="P", Q="window", Y="S")
    feats: list[str] = []
    for func in path_get(ast_, "body", 0, "expression", "elements"):
        if func is None:
            continue
        c = defaultdict(lambda: f"t{len(c) - 4}", G)
        node = path_get(func, "body", "body")
        feat = syntax_hash(node, c)
        feats.append(feat)
    return feats


def generate_opfeats(op_names: list[str], op_syntax: list[str], source_hint: str) -> str:
    if len(op_names) != len(op_syntax):
        raise RuntimeError(f"Mismatch: {len(op_names)} op names vs {len(op_syntax)} syntax hashes")

    op_feats = [md5(feat.encode()).hexdigest() for feat in op_syntax]

    lines: list[str] = [
        "# AUTO-GENERATED BY scripts/generate_opfeats.py",
        f"# Source: {source_hint}",
        "# Do not edit manually.",
        "",
        "from typing import Tuple",
        "",
        "# fmt: off",
        f"OP_COUNT: int = {len(op_names)}",
        "",
        "OP_NAMES: Tuple[str, ...] = (",
    ]
    for name in op_names:
        lines.append(f'    "{name}",')
    lines.extend([")", "", "OP_SYNTAX: Tuple[str, ...] = ("])
    for i, feat in enumerate(op_syntax):
        escaped = feat.replace("\\", "\\\\").replace('"', '\\"')
        lines.append(f'    "{escaped}",  # {i}: {op_names[i]}')
    lines.extend([")", "", "OP_FEATS: Tuple[str, ...] = ("])
    for i, h in enumerate(op_feats):
        lines.append(f'    "{h}",  # {i}: {op_names[i]} -- {op_syntax[i]}')
    lines.extend([")", "# fmt: on", ""])

    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="Generate opfeats.py from a ChaosVM JS snippet and vm.py."
    )
    parser.add_argument(
        "--js",
        "-j",
        type=Path,
        default=Path("js/snippet/U.js"),
        help="Path to the ChaosVM JS snippet (default: js/snippet/U.js)",
    )
    parser.add_argument(
        "--output",
        "-o",
        type=Path,
        default=Path("src/chaosvm/opfeats.py"),
        help="Output path for opfeats.py (default: src/chaosvm/opfeats.py)",
    )
    args = parser.parse_args(argv)

    js_path: Path = args.js
    output_path: Path = args.output

    if not VM_PY_PATH.exists():
        print(f"ERROR: {VM_PY_PATH} not found", file=sys.stderr)
        return 1
    if not js_path.exists():
        print(f"ERROR: {js_path} not found", file=sys.stderr)
        return 1

    op_names = extract_op_names()
    op_syntax = extract_op_syntax(js_path)

    content = generate_opfeats(op_names, op_syntax, source_hint=str(js_path).replace("\\", "/"))
    output_path.write_text(content, encoding="utf-8")
    print(f"Generated {output_path} with {len(op_names)} opcodes.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
