#!/usr/bin/env python3
"""Generate opfeats.py from ChaosVM JS snippets and the BuiltinOps implementation.

Supports both funarr-style (U.js) and switch-style (V.js) VM instruction sets.
"""

from __future__ import annotations

import argparse
import sys
from collections import defaultdict
from hashlib import md5
from pathlib import Path

from pyjsparser import parse

from chaosvm.parse import path_get
from chaosvm.stxhash import syntax_hash

PROJECT_ROOT = Path(__file__).parent.parent
VM_PY_PATH = PROJECT_ROOT / "src" / "chaosvm" / "vm_funarr.py"


def extract_op_names(vm_py_path: Path = VM_PY_PATH) -> list[str]:
    """Parse vm.py and extract the ordered list of opcode method names from self.ops."""
    from chaosvm.vm_funarr import FunarrOps

    return [f.__name__ for f in FunarrOps.ops]


def extract_op_syntax(u_js_path: Path) -> list[str]:
    """Parse U.js and return the ordered list of syntax-hash strings for opcodes."""
    source = u_js_path.read_text(encoding="utf-8")
    ast_ = parse(source)

    G = dict(k="p", B="P", Q="window", Y="S")
    feats: list[str] = []
    for func in path_get(ast_, "body", 0, "expression", "elements"):
        if func is None:
            continue
        c = defaultdict(lambda: f"t{len(c) - 4}", G)
        node = path_get(func, "body", "body")
        feat = syntax_hash(node, c)
        feats.append(feat)
    return feats


def extract_switch_op_info(switch_js_path: Path) -> tuple[list[str], list[str]]:
    """Parse V.js (switch block) and return (op_names, op_syntax) for switch-style VM.

    V.js contains just the switch statement with cases 0-95.
    Each case corresponds to one opcode.
    """
    source = switch_js_path.read_text(encoding="utf-8")
    # Wrap in a function since V.js has return statements at case level
    wrapped = f"function _vm() {{ {source} }}"
    ast_ = parse(wrapped)

    op_names: list[str] = []
    op_syntax: list[str] = []

    # V.js structure (wrapped): FunctionDeclaration -> BlockStatement -> SwitchStatement
    switch_stmt = path_get(ast_, "body", 0, "body", "body", 0)
    if switch_stmt["type"] != "SwitchStatement":
        raise RuntimeError(f"Expected SwitchStatement, got {switch_stmt['type']}")

    cases = switch_stmt["cases"]
    for case in cases:
        case_num = case["test"]["value"] if case["test"] else None
        if case_num is not None and isinstance(case_num, (int, float)):
            # Extract case body (statements before break)
            case_body = case["consequent"]
            # Generate syntax hash from case body
            G = {c: c for c in "RKoQCUwTSYIGF"}
            c = defaultdict(lambda: f"t{len(c)}", G)
            feat = syntax_hash(case_body, c)
            op_syntax.append(feat)
            op_names.append(f"op_{int(case_num)}")

    # Sort by case number to ensure correct order
    sorted_pairs = sorted(zip(op_names, op_syntax), key=lambda x: int(x[0].split("_")[1]))
    op_names = [p[0] for p in sorted_pairs]
    op_syntax = [p[1] for p in sorted_pairs]

    return op_names, op_syntax


def generate_opfeats(
    funarr_names: list[str],
    funarr_syntax: list[str],
    switch_names: list[str] | None = None,
    switch_syntax: list[str] | None = None,
) -> str:
    """Generate opfeats.py content for one or both VM types."""
    lines: list[str] = [
        "# AUTO-GENERATED BY scripts/generate_opfeats.py",
        "# Sources: js/snippet/U.js (funarr), js/snippet/switch.js (switch)",
        "# Do not edit manually.",
        "",
        "from typing import Tuple",
        "",
        "# fmt: off",
        "",
        "# ============ Funarr VM (58 ops) ============",
        f"FUNARR_OP_COUNT: int = {len(funarr_names)}",
        "",
        "FUNARR_OP_NAMES: Tuple[str, ...] = (",
    ]
    for name in funarr_names:
        lines.append(f'    "{name}",')
    lines.extend([")", "", "FUNARR_OP_SYNTAX: Tuple[str, ...] = ("])
    for i, feat in enumerate(funarr_syntax):
        escaped = feat.replace("\\", "\\\\").replace('"', '\\"')
        lines.append(f'    "{escaped}",  # {i}: {funarr_names[i]}')

    funarr_feats = [md5(feat.encode()).hexdigest() for feat in funarr_syntax]
    lines.extend([")", "", "FUNARR_OP_FEATS: Tuple[str, ...] = ("])
    for i, h in enumerate(funarr_feats):
        lines.append(f'    "{h}",  # {i}: {funarr_names[i]}')
    lines.extend([")", ""])

    # Add switch VM info if provided
    if switch_names and switch_syntax:
        lines.extend(
            [
                "",
                "# ============ Switch VM (96 ops) ============",
                f"SWITCH_OP_COUNT: int = {len(switch_names)}",
                "",
                "SWITCH_OP_NAMES: Tuple[str, ...] = (",
            ]
        )
        for name in switch_names:
            lines.append(f'    "{name}",')
        lines.extend([")", "", "SWITCH_OP_SYNTAX: Tuple[str, ...] = ("])
        for i, feat in enumerate(switch_syntax):
            escaped = feat.replace("\\", "\\\\").replace('"', '\\"')
            lines.append(f'    "{escaped}",  # {i}: {switch_names[i]}')

        switch_feats = [md5(feat.encode()).hexdigest() for feat in switch_syntax]
        lines.extend([")", "", "SWITCH_OP_FEATS: Tuple[str, ...] = ("])
        for i, h in enumerate(switch_feats):
            lines.append(f'    "{h}",  # {i}: {switch_names[i]}')
        lines.extend([")", ""])

    lines.extend(
        [
            "",
            "# Aliases for backward compatibility",
            "OP_COUNT = FUNARR_OP_COUNT",
            "OP_NAMES = FUNARR_OP_NAMES",
            "OP_SYNTAX = FUNARR_OP_SYNTAX",
            "OP_FEATS = FUNARR_OP_FEATS",
            "",
            "# fmt: on",
            "",
        ]
    )

    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="Generate opfeats.py from ChaosVM JS snippets and vm.py."
    )
    parser.add_argument(
        "--funarr-js",
        type=Path,
        default=Path("js/snippet/U.js"),
        help="Path to the funarr-style JS snippet (default: js/snippet/U.js)",
    )
    parser.add_argument(
        "--switch-js",
        type=Path,
        default=Path("js/snippet/V.js"),
        help="Path to the switch-style JS snippet (default: js/snippet/V.js)",
    )
    parser.add_argument(
        "--output",
        "-o",
        type=Path,
        default=Path("src/chaosvm/opfeats.py"),
        help="Output path for opfeats.py (default: src/chaosvm/opfeats.py)",
    )
    args = parser.parse_args(argv)

    funarr_js: Path = args.funarr_js
    switch_js: Path = args.switch_js
    output_path: Path = args.output

    if not VM_PY_PATH.exists():
        print(f"ERROR: {VM_PY_PATH} not found", file=sys.stderr)
        return 1
    if not funarr_js.exists():
        print(f"ERROR: {funarr_js} not found", file=sys.stderr)
        return 1

    print("Extracting funarr op info...")
    funarr_names = extract_op_names()
    funarr_syntax = extract_op_syntax(funarr_js)
    print(f"  Found {len(funarr_names)} funarr opcodes")

    switch_names: list[str] | None = None
    switch_syntax: list[str] | None = None
    if switch_js.exists():
        print("Extracting switch op info...")
        switch_names, switch_syntax = extract_switch_op_info(switch_js)
        print(f"  Found {len(switch_names)} switch opcodes")
    else:
        print("Switch JS not found, generating funarr-only opfeats")

    content = generate_opfeats(funarr_names, funarr_syntax, switch_names, switch_syntax)
    output_path.write_text(content, encoding="utf-8")
    total = len(funarr_names) + (len(switch_names) if switch_names else 0)
    print(f"Generated {output_path} with {total} total opcodes.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
