# install dependency and current package
name: Test uv Project

on:
  pull_request:
    types:
      - review_requested
      - opened
    branches:
      - beta
      - release

concurrency:
  group: test-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  install-test:
    if: github.event_name != 'pull_request' || github.event.action != 'opened' || startsWith(github.head_ref, 'deps/')
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.14", "3.11", "3.10"]
    steps:
      #----------------------------------------------
      #   check-out repo and set-up node & python
      #----------------------------------------------
      - uses: actions/checkout@v6
      - uses: astral-sh/setup-uv@v7
        with:
          python-version: ${{ matrix.python-version }}
          activate-environment: true
          enable-cache: true

      - name: Install and Test
        run: |
          echo "::group::Install Dependencies"
          uv sync --no-default-groups --group test
          echo "::endgroup::"

          echo "::group::Check generated opcode features"
          uv run python scripts/generate_opfeats.py
          git diff --exit-code src/chaosvm/opfeats.py
          echo "::endgroup::"

          echo "::group::pytest outputs"
          uv run pytest tests --log-cli-level=WARNING
          echo "::endgroup::"
